### PR TITLE
Release 1.0.0

### LINKED ISSUE #65: Source code on github and pypi differs
I noticed that `Flask-Bcrypt==0.7.1` installed from pypi is not the same found in this repo (no matter it's 0.7.1 too https://github.com/maxcountryman/flask-bcrypt/blob/13df85ab1b4d7602a967c7ec1c6707c8cda459c6/flask_bcrypt.py)

here's comparison pypi vs repo (repo is newer)

```diff
4,6c4,6
<     
<     A Flask extension providing bcrypt hasing and comparison facilities.
<     
---
> 
>     A Flask extension providing bcrypt hashing and comparison facilities.
> 
28a29,30
> import hashlib
> 
40,41c42,44
<     To this this function, simple import it from the module and use it in a 
<     similar fashion as the method would be used. Here is a quick example::
---
>     To use this function, simply import it from the module and use it in a 
>     similar fashion as the original method would be used. Here is a quick
>     example::
43c46
<         from flask.ext.bcrypt import generate_password_hash
---
>         from flask_bcrypt import generate_password_hash
57,61c60,65
<     
<     To this this function, simple import it from the module and use it in a 
<     similar fashion as the method would be used. Here is a quick example::
<         
<         from flask.ext.bcrypt import check_password_hash
---
> 
>     To use this function, simply import it from the module and use it in a 
>     similar fashion as the original method would be used. Here is a quick
>     example::
> 
>         from flask_bcrypt import check_password_hash
63c67
<     
---
> 
119c123,138
<     
---
> 
>     You may also set the hash version using the `BCRYPT_HASH_PREFIX` field in
>     the configuration of the Flask app. If not set, this will default to `2b`.
>     (See bcrypt for more details)
> 
>     By default, the bcrypt algorithm has a maximum password length of 72 bytes
>     and ignores any bytes beyond that. A common workaround is to hash the
>     given password using a cryptographic hash (such as `sha256`), take its
>     hexdigest to prevent NULL byte problems, and hash the result with bcrypt.
>     If the `BCRYPT_HANDLE_LONG_PASSWORDS` configuration value is set to `True`,
>     the workaround described above will be enabled.
>     **Warning: do not enable this option on a project that is already using
>     Flask-Bcrypt, or you will break password checking.**
>     **Warning: if this option is enabled on an existing project, disabling it
>     will break password checking.**
> 
123a143,144
>     _prefix = '2b'
>     _handle_long_passwords = False
135,139c156,181
<     
<     def generate_password_hash(self, password, rounds=None):
<         '''Generates a password hash using bcrypt. Specifying `rounds` 
<         sets the log_rounds parameter of `bcrypt.gensalt()` which determines 
<         the complexity of the salt. 12 is the default value.
---
>         self._prefix = app.config.get('BCRYPT_HASH_PREFIX', '2b')
>         self._handle_long_passwords = app.config.get(
>             'BCRYPT_HANDLE_LONG_PASSWORDS', False)
> 
>     def _unicode_to_bytes(self, unicode_string):
>         '''Converts a unicode string to a bytes object.
> 
>         :param unicode_string: The unicode string to convert.'''
>         if PY3:
>             if isinstance(unicode_string, str):
>                 bytes_object = bytes(unicode_string, 'utf-8')
>             else:
>                 bytes_object = unicode_string
>         else:
>             if isinstance(unicode_string, unicode):
>                 bytes_object = unicode_string.encode('utf-8')
>             else:
>                 bytes_object = unicode_string
>         return bytes_object
> 
>     def generate_password_hash(self, password, rounds=None, prefix=None):
>         '''Generates a password hash using bcrypt. Specifying `rounds`
>         sets the log_rounds parameter of `bcrypt.gensalt()` which determines
>         the complexity of the salt. 12 is the default value. Specifying `prefix`
>         sets the `prefix` parameter of `bcrypt.gensalt()` which determines the 
>         version of the algorithm used to create the hash.
147a190
>         :param prefix: The algorithm version to use.
154a198,199
>         if prefix is None:
>             prefix = self._prefix
157,158c202,203
<         if PY3 and isinstance(password, str):
<             password = bytes(password, 'utf-8')
---
>         password = self._unicode_to_bytes(password)
>         prefix = self._unicode_to_bytes(prefix)
160,161c205,207
<         if not PY3 and isinstance(password, unicode):
<             password = password.encode('utf-8')
---
>         if self._handle_long_passwords:
>             password = hashlib.sha256(password).hexdigest()
>             password = self._unicode_to_bytes(password)
163c209,210
<         return bcrypt.hashpw(password, bcrypt.gensalt(rounds))
---
>         salt = bcrypt.gensalt(rounds=rounds, prefix=prefix)
>         return bcrypt.hashpw(password, salt)
181,182c228,229
<         if PY3 and isinstance(pw_hash, str):
<             pw_hash = bytes(pw_hash, 'utf-8')
---
>         pw_hash = self._unicode_to_bytes(pw_hash)
>         password = self._unicode_to_bytes(password)
184,185c231,233
<         if PY3 and isinstance(password, str):
<             password = bytes(password, 'utf-8')
---
>         if self._handle_long_passwords:
>             password = hashlib.sha256(password).hexdigest()
>             password = self._unicode_to_bytes(password)
187,192d234
<         if not PY3 and isinstance(pw_hash, unicode):
<             pw_hash = pw_hash.encode('utf-8')
< 
<         if not PY3 and isinstance(password, unicode):
<             password = password.encode('utf-8')
< 
194d235
< 
```

pypi was updated a long time ago and lacks such features as `long_passwords` and etc

___
```
bcrypt==3.2.0
Flask-Bcrypt==0.7.1
```

### PR DESCRIPTION
**Pull request by mahenzon**
Closes #65 

To match source code and release I suggest using automatic releases

pls add `PYPI_PASSWORD` to repo's `secrets` and create a new release, package be automatically deployed to pypi

I suggest updating version to 1.0.0

### CODE REVIEW

**Comment by maxcountryman** [comment]
Thanks for this!

I'm not super comfortable using my PyPI password for this--could we do something like what [Flask-SeaSurf is doing](https://github.com/maxcountryman/flask-seasurf/pull/98) instead?

**Comment by mahenzon** [comment]
you don't need to use your real password for PYPI, you need to generate auth token:

```
We strongly recommend you authenticate with an API token where possible.
To make an API token:
- Verify your email address (check your account settings)
- In your account settings, go to the API tokens section and select "Add API token"

To use an API token:
- Set your username to __token__
- Set your password to the token value, including the pypi- prefix
```
https://pypi.org/help/#apitoken

you can limit scope for each token so it has access only to the selected repo

I think you're confused with `PYPI_PASSWORD` but it's api token (in `flask-seasurf` it's the same thing but is called `PYPI_API_TOKEN`). pls take a look at the action, `__token__` auth is used there

I can rename it for your convenience if you'd like

**Comment by mahenzon** [comment]
@maxcountryman hey!

still waiting your action here
you need to:

1. merge this branch into master
2. add `PYPI_PASSWORD` secret with pypi api token which has write (update) access to the flask-bcrypt repo
3. tag commit with 1.0.0
4. create a new release here on github

this will take like 5-7m max

**Comment by maxcountryman** [comment]
Thanks @mahenzon--do you mind updating this so it mirrors the configuration in Flask-SeaSurf? That'll help limit the mental overhead required to maintain these repos.

**Comment by mahenzon** [comment]
you mean changing `PYPI_PASSWORD` to `PYPI_API_TOKEN`? 
or also use `pypa/gh-action-pypi-publish`? inside it also `twine upload` is triggered so technically publish process is the same

**Comment by maxcountryman** [comment]
I think you could just copy the workflow from Flask-SeaSurf and update accordingly for this repo, if that's helpful. That way it's reusing the same Action, etc.

**Comment by mahenzon** [comment]
ok, upgraded the action

now steps are:

1. merge this branch into master
2. add `PYPI_API_TOKEN` with write (update) access to the flask-bcrypt repo
3. add tag to the latest commit (tag it with `1.0.0`) - release action will be triggered

**Comment by mahenzon** [comment]
hey @maxcountryman , it's the final push and this issue will be resolved. three steps to do, doable even from mobile 🙏

**Comment by mahenzon** [comment]
@maxcountryman 👀

**Comment by mahenzon** [comment]
🤔

**Comment by mahenzon** [comment]
🧐

**Comment by mahenzon** [comment]
Max, at first I wanna say that I hope you're doing well

Flask-Bcrypt [at pypi](https://pypi.org/project/Flask-Bcrypt/) was Released: Oct 6, 2015. This repo got some updates from users, but there were no releases for more than 5 years.

The only thing stopping this repo from being updated now is you adding secret key for pypi releases and merging this branch. 
I can do it as well. For this you can add me as maintainer here (at this repo) and also add me as maintainer/owner at repo's settings: https://pypi.org/manage/project/Flask-Bcrypt/collaboration/ (here's my profile https://pypi.org/user/mahenzon/)
This PR is active for 3 weeks already, but the solution is like 5 minutes or so

**Comment by maxcountryman** [comment]
@mahenzon would you kindly stop pinging me about this? I'll get to it when I have the time and your many messages aren't encouraging me to prioritize this.

**Comment by mahenzon** [comment]
Hey!
I think it's not about having free time, but about having (or not having) an aspiration to do this. It's literally only about hitting "merge", adding a token to secrets and pushing a new tag (a new tag can be added via GitHub releases) - this all can be done while commuting/being in an elevator/waiting for lunch/etc. Our conversation already took more than that time plus time I spent on adding a GitHub action/workflow file and time I spent on updating it to meet your requirements. 
This repo is marked as "Used by 23k" - we can see that this library is used by a lot of people. When I opened this pull request this number was 19k or 21k (cannot remember now). And people use the outdated version.

So could you please grant me access to this repo and at pypi so I can finally release what's already been here for years in the master branch?

**Comment by maxcountryman** [comment]
Thank you I appreciate your concerns but there's nothing stopping you from using mainline (as others do).

I'm going to close this because I already mentioned that your multiple messages were sufficient and it's not okay to continue to demand anyone's time, however little you perceive the cost.

If you'd like to arrange to pay me to do this work for you then I'd be happy to share my daily rate with you.

**Pull request closed without merging**
